server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: root
  password:
  dbname: auth_service
  sslmode: disable
  max_connection_pool: 10
  max_idle_time: 5
  max_lifetime_pool: 30

jwt:
  jwt_secret:
  jwt_expire_in_minutes: 60

OAuth:
  client_id:
  client_secret:
